
UPDATE supplier_profiles 
SET family_dictionary = '[
  {"contains":["smartlife"],"family_id":"ZEISS_FAM_2026","priority":5},
  {"contains":["smartlife","lg pr"],"family_id":"ZEISS_FAM_2015","priority":3},
  {"contains":["individual 3","lg pr"],"family_id":"ZEISS_FAM_2012","priority":3},
  {"contains":["individual 3","lg vs"],"family_id":"ZEISS_FAM_2024","priority":3},
  {"contains":["superb","lg pr"],"family_id":"ZEISS_FAM_2013","priority":5},
  {"contains":["plus","lg pr"],"family_id":"ZEISS_FAM_2014","priority":5},
  {"contains":["pure","lg pr"],"family_id":"ZEISS_FAM_2015","priority":5},
  {"contains":["essential","lg pr"],"family_id":"ZEISS_FAM_2016","priority":5},
  {"contains":["essential short"],"family_id":"ZEISS_FAM_2017","priority":3},
  {"contains":["light 2 3dv"],"family_id":"ZEISS_FAM_2018","priority":2},
  {"contains":["light 2 3d"],"family_id":"ZEISS_FAM_2019","priority":3},
  {"contains":["light 2 d"],"family_id":"ZEISS_FAM_2020","priority":3},
  {"contains":["light 2","lg vs"],"family_id":"ZEISS_FAM_2028","priority":5},
  {"contains":["energizeme"],"family_id":"ZEISS_FAM_2036","priority":5},
  {"contains":["drivesafe","lg pr"],"family_id":"ZEISS_FAM_2038","priority":3},
  {"contains":["drivesafe","lg vs"],"family_id":"ZEISS_FAM_2039","priority":3},
  {"contains":["clearview"],"family_id":"ZEISS_FAM_2031","priority":5},
  {"contains":["classicplus","lg pr"],"family_id":"ZEISS_FAM_2022","priority":5},
  {"contains":["classicplus","lg vs"],"family_id":"ZEISS_FAM_2035","priority":5},
  {"contains":["blueprotect"],"family_id":"ZEISS_FAM_2134","priority":5},
  {"contains":["myocare s"],"family_id":"ZEISS_FAM_2033","priority":2},
  {"contains":["myocare"],"family_id":"ZEISS_FAM_2032","priority":5},
  {"contains":["office superb near"],"family_id":"ZEISS_FAM_2042","priority":2},
  {"contains":["office superb room"],"family_id":"ZEISS_FAM_2041","priority":2},
  {"contains":["office ind"],"family_id":"ZEISS_FAM_2040","priority":5},
  {"contains":["ind sport","lg pr"],"family_id":"ZEISS_FAM_2043","priority":3},
  {"contains":["ind sport","lg vs"],"family_id":"ZEISS_FAM_2044","priority":3},
  {"contains":["ind lenses"],"family_id":"ZEISS_FAM_2037","priority":5},
  {"contains":["choice"],"family_id":"ZEISS_FAM_2052","priority":5},
  {"contains":["synchrony easy adapt"],"family_id":"ZEISS_FAM_2050","priority":2},
  {"contains":["synchrony easy view"],"family_id":"ZEISS_FAM_627","priority":2},
  {"contains":["synchrony office"],"family_id":"ZEISS_FAM_2047","priority":3},
  {"contains":["synchrony solamax"],"family_id":"ZEISS_FAM_2051","priority":3},
  {"contains":["synchrony","lg vs"],"family_id":"ZEISS_FAM_2049","priority":8},
  {"contains":["young"],"family_id":"ZEISS_FAM_2025","priority":5}
]'::jsonb,
updated_at = now()
WHERE supplier_code = 'ZEISS';
